/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.PacienteControlador;
import java.awt.Frame;

/**
 *
 * @author Alvaro
 */
public class DlgVistaPacientes extends javax.swing.JDialog {
    
    Frame parentFrame;
    PacienteControlador controlador = new PacienteControlador();

    /**
     * Creates new form DlgVistaPacientes
     */
    public DlgVistaPacientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        parentFrame = parent;
        initComponents();
        this.setLocationRelativeTo(null);
        cargarListaPacientes();
    }
    
    public void cargarListaPacientes() {
        try {
            tblPacientes.setModel(controlador.listarPacientes());
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        srcPacientes = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        btnNuevoPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTitulo.setText("Pacientes");

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacientesMouseClicked(evt);
            }
        });
        srcPacientes.setViewportView(tblPacientes);

        btnNuevoPaciente.setText("Nuevo paciente");
        btnNuevoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(srcPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(btnNuevoPaciente))
                .addGap(30, 30, 30)
                .addComponent(srcPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPacienteActionPerformed
        DlgNuevoPaciente dlgNuevoPaciente = new DlgNuevoPaciente(parentFrame, true);
        dlgNuevoPaciente.setVisible(true);
        cargarListaPacientes();
    }//GEN-LAST:event_btnNuevoPacienteActionPerformed

    private void tblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseClicked
        int filaSeleccionada = tblPacientes.getSelectedRow();
        
        DlgEditarPaciente dlgEditarPaciente = new DlgEditarPaciente(parentFrame, true);
        dlgEditarPaciente.idPaciente = tblPacientes.getModel().getValueAt(filaSeleccionada, 0).toString();
        dlgEditarPaciente.nombrePaciente = tblPacientes.getModel().getValueAt(filaSeleccionada, 1).toString();
        dlgEditarPaciente.apellidoPaciente = tblPacientes.getModel().getValueAt(filaSeleccionada, 2).toString();
        dlgEditarPaciente.direcPaciente = tblPacientes.getModel().getValueAt(filaSeleccionada, 3).toString();
        dlgEditarPaciente.fechaNacPaciente = tblPacientes.getModel().getValueAt(filaSeleccionada, 4).toString();
        dlgEditarPaciente.dniPaciente = tblPacientes.getModel().getValueAt(filaSeleccionada, 5).toString();
        dlgEditarPaciente.celularPaciente = tblPacientes.getModel().getValueAt(filaSeleccionada, 6).toString();
        
        dlgEditarPaciente.setVisible(true);
        cargarListaPacientes();
    }//GEN-LAST:event_tblPacientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoPaciente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane srcPacientes;
    private javax.swing.JTable tblPacientes;
    // End of variables declaration//GEN-END:variables
}
